New survey header
haniszewski/survey-system-frontend pull request #8
Opened 2023-12-13 18:45 UTC by JanCzop

2023-12-13 19:23 UTC, DawidZZ requested changes

2023-12-13 19:23 UTC, DawidZZ commented on src/components/molecules/create-survey/new-survey-header.tsx
> +              htmlFor="surveyDescription"
opis chyba wyjebujemy, bo na backendzie go nie ma

2023-12-13 19:23 UTC, DawidZZ commented on src/components/molecules/create-survey/new-survey-header.tsx
> +              type="date"
jeśli to działa to trzeba do TextFormField dodać do typu "date" żeby się eslint nie czepiał

2023-12-13 19:23 UTC, DawidZZ commented on src/components/molecules/create-survey/new-survey-header.tsx
> +              name="surveyStartDate"
name="start_date"

2023-12-14 11:30 UTC, JanCzop reviewed
zmienilem na uzywanie tylko useFormContext
poustawialem te przyciski jak w pytaniu
do textfielda dodalem typ date i pole classname zeby sie nie czepial eslint
tylko przy tych datach i dayjs sie czepia o unsafe argument

2023-12-14 20:02 UTC, merged